import Head from 'next/head'

export default function Home() {
    return <div>
        <Head>
            <title>Public Data Sets | Queries Are Us</title>
            <meta name="description" content="Generated by create next app" />
            <base href={process.env.BASE_ADDRESS} />
            <link rel="icon" href="/qau_logo_sglm.png" />
        </Head>

        <main>
            <h1>Data Sets</h1>
            <h2>Main sets:</h2>
            <ul>
                <li><a href='/api/ds/conferences' target="_blank" rel="noopener noreferrer">/api/ds/conferences</a></li>
            </ul>
        </main>

        <footer>
            <a className='link_website' href="https://www.queries-are-us.com/" target="_blank" rel="noopener noreferrer">
                Website UI
            </a>
            <a className='link_repo' href="https://github.com/queries-are-us/public_data-sets" target="_blank" rel="noopener noreferrer">
                GitHub Repo
            </a>
            <a className='link_licence' href="https://github.com/queries-are-us/public_data-sets/blob/main/LICENSE" target="_blank" rel="noopener noreferrer">
                Licence
            </a>
        </footer>
    </div>
}
